site_name: The Atlas Model
site_description: "Engine, equations, and conductor for resonance across scales"
site_url: https://terralanmira.github.io/The-Atlas-Model/
repo_url: https://github.com/terralanmira/The-Atlas-Model
repo_name: terralanmira/The-Atlas-Model

theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
  - attr_list
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic

plugins:
  - search

nav:
  - Home: docs/index.md

  - Atlas (Bridge & Discipline):
      - Bridge (Atlas ↔ Resonant Reality): docs/atlas/ResonantReality_Bridge.md
      - Bridge Handshake (Data I/O): docs/atlas/bridge_handshake.md
      - Awareness Levels (Mirror → Chamber → Conductor): docs/atlas/awareness_levels.md
      - Scan (Operational Discipline): docs/atlas/scan.md
      - Model Index: docs/atlas/Model_Index.md
      - Conductor’s Score: docs/atlas/Conductors_Score.md

  - Awareness (Signals & Frameworks):
      - Signals Guide: docs/awareness/signals_guide.md
      - Resonant Frameworks: docs/awareness/Resonant_Frameworks.md
      - Resonant Synthesis: docs/awareness/Resonant_Synthesis.md
      - Harmonic Slip Template: docs/awareness/Harmonic_Slip_Template.md
      - R_Growth Algorithm: docs/awareness/R_Growth.md
      - Atlas 3.0 Schematics: docs/awareness/Atlas_3_Schematics.md

  - Field (01–08):
      - 01 Ley Lines: docs/field/01_Ley_Lines.md
      - 02 Geomagnetic: docs/field/02_Geomagnetic.md
      - 03 Sacred Nodes: docs/field/03_Sacred_Nodes.md
      - 04 Axis Mundi: docs/field/04_Axis_Mundi.md
      - 05 Resonant Architecture: docs/field/05_Resonant_Architecture.md
      - 06 Cosmic Alignments: docs/field/06_Cosmic_Alignments.md
      - 07 Suppression & Rediscovery: docs/field/07_Suppression_Rediscovery.md
      - 08 The Whole Field: docs/field/08_The_Whole_Field.md

  - Applications:
      - Dual-Phase Field: docs/applications/Dual_Phase_Field.md
      - Soul-in-Field: docs/applications/Soul_in_Field.md
      - Stress Tests: docs/applications/Stress_Tests.md

  - LLM Conductor:
      - Overview: docs/llm/index.md
      - System Persona: llm/system/atlas_system_prompt.md
      - Role Seeds: llm/roles_prompts.md
      - Router Rules: llm/router_rules.md
      - Scorer Rules: llm/scorer_rules.md
      - Evals (Prompts): llm/evals/prompts.md

  - Spec:
      - Infinity Equation: docs/spec/infinity_equation.md
      - Resonance Interfaces: docs/spec/resonance_interfaces.md

  - Ethics & Contributing:
      - Ethics: ETHICS.md
      - Contributing: CONTRIBUTING.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/terralanmira/The-Atlas-Model
      name: GitHub
