site_name: The Atlas Model
site_description: "Engine, equations, and practice for resonance across scales"
site_url: https://terralanmira.github.io/The-Atlas-Model/
repo_url: https://github.com/terralanmira/The-Atlas-Model
repo_name: terralanmira/The-Atlas-Model

theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
  - attr_list
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic

plugins:
  - search

nav:
  - Home: docs/index.md

  - Atlas:
      - Model Index: docs/atlas/Model_Index.md
      - Bridge (Atlas ↔ Resonant Reality): docs/atlas/ResonantReality_Bridge.md
      - Atlas Bridge (Internal): docs/atlas/Atlas_Bridge.md
      - Conductor’s Score: docs/atlas/Conductors_Score.md

  - Field (01–08):
      - 01 Ley Lines: docs/field/01_Ley_Lines.md
      - 02 Geomagnetic: docs/field/02_Geomagnetic.md
      - 03 Sacred Nodes: docs/field/03_Sacred_Nodes.md
      - 04 Axis Mundi: docs/field/04_Axis_Mundi.md
      - 05 Resonant Architecture: docs/field/05_Resonant_Architecture.md
      - 06 Cosmic Alignments: docs/field/06_Cosmic_Alignments.md
      - 07 Suppression & Rediscovery: docs/field/07_Suppression_Rediscovery.md
      - 08 The Whole Field: docs/field/08_The_Whole_Field.md

  - Awareness:
      - Resonant Frameworks: docs/awareness/Resonant_Frameworks.md
      - Resonant Synthesis: docs/awareness/Resonant_Synthesis.md
      - Harmonic Slip Template: docs/awareness/Harmonic_Slip_Template.md
      - R_Growth Algorithm: docs/awareness/R_Growth.md
      - Atlas 3.0 Schematics: docs/awareness/Atlas_3_Schematics.md

  - Applications:
      - Dual-Phase Field: docs/applications/Dual_Phase_Field.md
      - Soul-in-Field: docs/applications/Soul_in_Field.md
      - Stress Tests: docs/applications/Stress_Tests.md

  - LLM:
      - Overview: docs/llm/index.md

  - Spec:
      - Overview: docs/spec/index.md
      - Infinity Equation: docs/spec/infinity_equation.md
      - Resonance Interfaces: docs/spec/resonance_interfaces.md

  - API:
      - Overview: docs/api/index.md

  - Design:
      - Principles: docs/design/principles.md

  - Bridge (Cross-Repo Overview): docs/bridge.md

  - Roadmap: docs/roadmap.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/terralanmira/The-Atlas-Model
      name: GitHub
