site_name: The Atlas Model
site_description: Fractal resonance, coherence, and conscious choice through The Atlas Model
site_author: Atlas Collective
repo_url: https://github.com/terralanmira/The-Atlas-Model
repo_name: The-Atlas-Model

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.action.edit

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list

nav:
  - Home: docs/index.md
  - Atlas (Whole):
      - Whole: docs/atlas_whole.md
      - Bridge: docs/bridge.md
      - Design: docs/atlas_design.md
      - Mind: docs/atlas_mind.md
      - Heart: docs/atlas_heart.md
      - Hands: docs/atlas_hands.md
      - Feet: docs/atlas_feet.md
      - Might: docs/atlas_might.md
      - Field: docs/atlas_field.md
      - Atlas Index: docs/atlas/Model_Index.md
  - Awareness:
      - Overview: docs/awareness/awareness_index.md
      - R Growth: docs/awareness/R_Growth.md
      - Harmonic Slip: docs/awareness/Harmonic_Slip_Template.md
      - Schematics: docs/awareness/Atlas_3_Schematics.md
  - Coherence: docs/coherence.md
  - Field Layers:
      - Overview: docs/field_layers.md
      - Flower of Life: docs/atlas/ResonantReality_Bridge.md
      - LC Grid Modes: sims/lc_grid_modes.py
  - Applications:
      - Soul in Field: docs/applications/Soul_in_Field.md
      - Dual Phase Field: docs/applications/Dual_Phase_Field.md
      - Stress Tests: docs/applications/Stress_Tests.md
  - Sims:
      - Kuramoto–Schumann Hybrid: sims/kuramoto_schumann_hybrid.py
      - Multi-Scale Kuramoto: sims/multi_scale_kuramoto.py
      - LC Grid Modes: sims/lc_grid_modes.py
  - Equations: docs/equations.md
  - Dashboard: docs/dashboard.md
  - LLM:
      - Roles & Prompts: llm/roles_prompts.md
      - Router Rules: llm/router_rules.md
      - Scorer Rules: llm/scorer_rules.md
      - System Prompt: llm/system/atlas_system_prompt.md
  - Sessions:
      - Schema: sessions/schema.json
      - Example Log: sessions/example_log.json
  - API:
      - Overview: docs/api/index.md
  - Spec:
      - Resonance Interfaces: docs/spec/resonance_interfaces.md
      - Infinity Equation: docs/spec/infinity_equation.md
