site_name: The Atlas Model
site_description: "Signal → Meaning → Form → Story → Action → Feedback → Integration → Meta-Coherence — a living, resonant model."
site_url: ""
repo_url: "https://github.com/TerralanMira/The-Atlas-Model"
repo_name: "TerralanMira/The-Atlas-Model"
copyright: "© The Atlas Model"

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mermaid2
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

nav:
  - Home: index.md

  - Foundations:
      - Awareness: awareness.md
      - Coherence: coherence.md
      - Field Layers: field_layers.md
      - Applications (Overview): applications.md

  - Meaning-Making:
      - Translation (Signal → Meaning): translation.md
      - Visualization (Meaning → Form): visualization.md
      - Narrative (Form → Story): narrative.md

  - Praxis:
      - Action (Story → Practice): action.md
      - Feedback (Closing the Loop): feedback.md
      - Integration (Concept): integration.md
      - Integration Layer (Operational): integration_layer.md

  - Evolution:
      - Meta-Coherence (Awareness of Awareness): meta_coherence.md
      - Atlas as Organism: atlas_as_organism.md
      - Embodiment Layer: embodiment_layer.md
      - Practice Layer: practice_layer.md
      - Transcendence & Grounding: transcendence_grounding.md
      - Transcendence Layer: transcendence_layer.md

  - Interfaces:
      - Dashboard: dashboard.md
      - Logs (Feed the Canopy): logs/README.md

  - LLM:
      - Atlas System Prompt: llm/atlas_system_prompt.md
