site_name: The Atlas Model
site_description: "A recursive framework for resonance, coherence, and embodied design."
site_author: "Atlas Contributors"
repo_url: "https://github.com/your-username/The-Atlas-Model"
repo_name: "The-Atlas-Model"

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.tabs.link

nav:
  - Home: index.md
  - The Whole: docs/whole.md
  - Awareness: docs/awareness.md
  - Coherence: docs/coherence.md
  - Field Layers: docs/field_layers.md
  - Applications: docs/applications.md
  - Integration: docs/integration.md
  - Body of Atlas:
      - Feet: docs/feet_of_atlas.md
      - Heart: docs/heart_of_atlas.md
      - Hands: docs/hands_of_atlas.md
      - Mind: docs/mind_of_atlas.md
      - Eyes: docs/eyes_of_atlas.md
      - Ears: docs/ears_of_atlas.md
      - Voice: docs/voice_of_atlas.md
  - Simulations:
      - Overview (Breath & Kuramoto): docs/sims/breath.md
      - Multi-Scale Kuramoto (code): sims/multi_scale_kuramoto.py
      - Breath Cycle (code): sims/breath_cycle.py
      - Presets (json): sims/presets.json
  - Dashboard:
      - Resonant Layer Overlays: dashboard/dashboard.py
  - LLM:
      - Atlas System Prompt: docs/llm/atlas_system_prompt.md
  - Ethics:
      - ETHICS (Consent • Transparency • Non-coercion): docs/meta/ETHICS.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
