site_name: The Atlas Model
site_description: "A recursive framework for resonance, coherence, and embodied design."
site_author: "Atlas Contributors"
repo_url: "https://github.com/your-username/The-Atlas-Model"
repo_name: "The-Atlas-Model"

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.tabs.link

nav:
  - Home: index.md
  - Spiral Map: docs/README.md
  - The Whole: docs/whole.md

  # — Ouroboros flow —
  - Awareness → Coherence:
      - Awareness (seed): docs/awareness.md
      - Coherence (thread): docs/coherence.md
  - Field Layers → Applications:
      - Field Layers (fabric): docs/field_layers.md
      - Applications (hands): docs/applications.md
  - Integration → Return:
      - Integration (weave): docs/integration.md
      - Return to Awareness (link): docs/awareness.md

  # — Embodiment —
  - Body of Atlas:
      - Feet: docs/feet_of_atlas.md
      - Heart: docs/heart_of_atlas.md
      - Hands: docs/hands_of_atlas.md
      - Mind: docs/mind_of_atlas.md
      - Eyes: docs/eyes_of_atlas.md
      - Ears: docs/ears_of_atlas.md
      - Voice: docs/voice_of_atlas.md

  # — Instruments —
  - Simulations:
      - Overview (Breath): docs/sims/breath.md
      - Breath Cycle (code): sims/breath_cycle.py
      - Multi-Scale Kuramoto (code): sims/multi_scale_kuramoto.py
      - Presets (json): sims/presets.json
  - Algorithms:
      - Coherence Metrics (code): algorithms/coherence_metrics.py

  # — Interface & Ethics —
  - LLM Conductor:
      - Atlas System Prompt: docs/llm/atlas_system_prompt.md
  - Dashboard:
      - Resonant Layer Overlays: dashboard/dashboard.py
  - Ethics:
      - ETHICS (Consent • Transparency • Non-coercion): docs/meta/ETHICS.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
