site_name: The Atlas Model
site_url: https://the-atlas-model.org
repo_url: https://github.com/TerralanMira/The-Atlas-Model
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: teal
      accent: cyan
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Dashboard: dashboard.md
  - Integration: integration.md
  - Resonant Reality:
      - Overview: resonant_reality/overview.md
      - Layers: resonant_reality/layers.md
      - Harmonics: resonant_reality/harmonics.md
  - Awareness & Coherence:
      - Awareness: awareness_coherence/awareness.md
      - Coherence: awareness_coherence/coherence.md
  - Field Layers:
      - Overview: field_layers.md
      - Water: field_layers/water.md
      - Air: field_layers/air.md
      - Fire & Plasma: field_layers/plasma.md
      - Crystals: field_layers/crystals.md
  - Field Applications:
      - Healing: field_applications/healing.md
      - Communication: field_applications/communication.md
      - Energy Systems: field_applications/energy.md
      - Simulations: field_applications/simulations.md
  - Algorithms:
      - Overview: algorithms/overview.md
      - Self-Learning Networks: algorithms/self_learning.md
      - Water-Air Dynamics: algorithms/water_air.md
      - Plasma: algorithms/plasma.md
      - Crystals: algorithms/crystals.md
      - Simulations: algorithms/simulations.md
  - Seeds:
      - Seed 1 – Origins: seeds/origins.md
      - Seed 2 – Coherence: seeds/coherence.md
      - Seed 3 – Expansion: seeds/expansion.md
      - Seed 4 – Applications: seeds/applications.md
      - Seed 5 – Future: seeds/future.md
  - Books:
      - Book I: books/book1.md
      - Book II: books/book2.md
      - Book III: books/book3.md
  - Exports:
      - Models: exports/models.md
      - Simulations: exports/simulations.md
      - Visuals: exports/visuals.md

plugins:
  - search
  - mkdocstrings
  - autorefs
  - macros

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TerralanMira/The-Atlas-Model
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/terralanmira
