site_name: The Atlas Model
site_description: Documentation of The Atlas Model – a recursive framework for resonance, coherence, and embodied design.
site_author: Atlas Contributors

theme:
  name: material
  palette:
    primary: indigo
    accent: deep purple
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.tabs.link

nav:
  - Home: index.md
  - Awareness: docs/awareness.md
  - Coherence: docs/coherence.md
  - Field Layers: docs/field_layers.md
  - Applications: docs/applications.md
  - Body of Atlas:
      - Feet: docs/feet_of_atlas.md
      - Heart: docs/heart_of_atlas.md
      - Hands: docs/hands_of_atlas.md
      - Mind: docs/mind_of_atlas.md
  - Voice of Atlas: docs/voice_of_atlas.md
  - LLM:
      - System Prompt: docs/llm/atlas_system_prompt.md

plugins:
  - search
  - mkdocs-mermaid2-plugin

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
