site_name: The Atlas Model
site_description: Fractal resonance, coherence, and conscious choice through The Atlas Model
site_author: Atlas Collective

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.action.edit

repo_url: https://github.com/terralanmira/The-Atlas-Model
repo_name: The-Atlas-Model

nav:
  - Home: index.md
  - Contributing: CONTRIBUTING.md
  - Ethics: ETHICS.md
  - Roadmap: docs/roadmap.md
  - Docs:
      - Awareness & Coherence:
          - Overview: docs/awareness/index.md
      - Field Layer:
          - Overview: docs/field/index.md
          - Layer 1: docs/field/layer1.md
          - Layer 2: docs/field/layer2.md
          - Layer 3: docs/field/layer3.md
          - Layer 4: docs/field/layer4.md
          - Layer 5: docs/field/layer5.md
          - Layer 6: docs/field/layer6.md
          - Layer 7: docs/field/layer7.md
          - Layer 8: docs/field/layer8.md
      - Applications:
          - Overview: docs/applications/index.md
          - Soul Equation: docs/applications/soul_equation.md
          - Dual-Phase Dynamics: docs/applications/dual_phase.md
          - Stress Tests: docs/applications/stress_tests.md
      - Atlas:
          - Model Specs: docs/atlas/specs.md
          - Bridge: docs/atlas/bridge.md
      - LLM:
          - Overview: docs/llm/index.md
          - Requirements: docs/llm/requirements.md
          - System Prompt: llm/system/atlas_system_prompt.md
  - Sims:
      - Overview: docs/sims/index.md
      - Kuramoto–Schumann Hybrid: sims/kuramoto_schumann_hybrid.py
      - LC Grid Modes: sims/lc_grid_modes.py
      - Multi-Scale Kuramoto: sims/multi_scale_kuramoto.py
  - Sessions:
      - Schema: sessions/schema.json
      - Example Log: sessions/example_log.json
