site_name: The Atlas Model
site_description: "An evolving framework of resonance, coherence, and fractal awareness."
site_author: "Atlas Project"
repo_url: "https://github.com/your-username/The-Atlas-Model"
repo_name: "The-Atlas-Model"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.highlight
    - toc.integrate
    - content.code.copy

nav:
  - Home: index.md

  - Atlas Foundations:
      - Feet of Atlas: docs/feet.md
      - Heart of Atlas: docs/heart.md
      - Mind of Atlas: docs/mind.md
      - Field of Atlas: docs/field_layers.md
      - Might of Atlas: docs/might.md

  - Awareness & Coherence:
      - Awareness: docs/awareness.md
      - Coherence: docs/coherence.md
      - Ouroboros (Cycle): docs/ouroboros.md
      - Relational Awareness (C·Δ·Φ): docs/relational_awareness.md

  - Simulations:
      - Sims Overview: docs/sims/index.md
      - Multi-Scale Kuramoto (code): sims/multi_scale_kuramoto.py
      - Presets (json): sims/presets.json

  - Dashboard:
      - Resonant Layer Overlays: docs/atlas/dashboard.md

  - Applications:
      - Applications: docs/applications.md

  - LLM System:
      - Atlas System Prompt: docs/llm/atlas_system_prompt.md

  - Ethics:
      - ETHICS (Consent • Transparency • Non-coercion): docs/meta/ETHICS.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
