site_name: The Atlas Model
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Resonant Reality: docs/resonant_reality.md
  - Books: docs/books.md
  - Awareness & Coherence:
      - Awareness: docs/awareness.md
      - Coherence: docs/coherence.md
  - Field Layer:
      - Overview: docs/field_layer.md
      - Water: docs/water.md
      - Air: docs/air.md
      - Fire & Plasma: docs/fire_plasma.md
      - Crystals: docs/crystals.md
  - Field Applications:
      - Overview: docs/field_applications.md
      - Ecology: docs/ecology.md
      - Health: docs/health.md
      - Community: docs/community.md
      - Algorithms & Simulations: docs/simulations.md
  - Synthesis:
      - Synthesis Layer: docs/synthesis_layer.md
      - Synthesis Patterns: docs/synthesis_patterns.md
  - Practice:
      - Practice Layer: docs/practice_layer.md
      - Integration: docs/integration.md
      - Integration Layer: docs/integration_layer.md
  - Convergence: docs/convergence.md
  - Emergence: docs/emergence_layer.md
  - Dashboard: docs/dashboard.md
  - Logs: docs/logs.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
