site_name: The Atlas Model
site_description: Hum ↔ Code — a living, fractal repository of resonance, coherence, and creation.
repo_url: https://github.com/TerralanMira/The-Atlas-Model
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.tabs.link
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Awareness & Coherence:
      - Awareness: awareness.md
      - Coherence: coherence.md
  - Field Layers:
      - Field Layers (Whole): field_layers.md
  - Applications: applications.md
  - LLM:
      - Atlas System Prompt: llm/atlas_system_prompt.md
  - Simulations:
      - Dashboard (What to Plot): dashboard.md
      - Creation (Genesis): creation.md
      - Creation — How to Read Births: creation_guide.md
  - Logs:
      - Feeding the Canopy: logs/README.md
