site_name: The Atlas Model
site_description: "An evolving framework of resonance, coherence, and fractal awareness."
site_author: "Atlas Project"
repo_url: "https://github.com/your-username/The-Atlas-Model"
repo_name: "The-Atlas-Model"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - Awareness & Coherence:
      - Awareness: docs/awareness.md
      - Coherence: docs/coherence.md
  - Field Layers:
      - Field Structure: docs/field_layers.md
      - Resonant Layer Overlays: docs/overlays.md
  - Applications:
      - Applications: docs/applications.md
      - Dashboard: docs/dashboard.md
  - Algorithms:
      - Coherence Metrics: algorithms/coherence_metrics.py
  - Simulations:
      - Multi-Scale Kuramoto: sims/multi_scale_kuramoto.py
      - Presets: sims/presets.json
  - LLM System:
      - Atlas System Prompt: docs/llm/atlas_system_prompt.md
  - Resonant Reality:
      - Overview: docs/resonant_reality.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/The-Atlas-Model
    - icon: fontawesome/solid/globe
      link: https://atlas-resonance.org
