name: Feature Request
description: Propose a new capability
labels: [type:feature, stage:speculation]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / User Story
      description: What pain or need?
      placeholder: "As a ..., I want ..., so that ..."
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Sketch the solution; include diagrams/links.
  - type: checkboxes
    id: signals
    attributes:
      label: Signals
      options:
        - label: signal:design
        - label: signal:math
        - label: signal:empirical
        - label: signal:docs
  - type: input
    id: area
    attributes:
      label: Area tags
      placeholder: "area:harmonics, area:observation"
