name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python toolchain
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov black ruff mypy mkdocs mkdocs-material

      - name: Lint & Format
        run: |
          ruff check .
          black --check .

      - name: Type Check
        run: mypy .

      - name: Tests
        run: pytest -q --disable-warnings --maxfail=1

      - name: Build Docs
        run: mkdocs build --strict
