name: ci
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov mypy black ruff mkdocs mkdocs-material mkdocs-jupyter

      - name: Lint (ruff + black --check)
        run: |
          ruff check .
          black --check .

      - name: Type check (mypy)
        run: mypy .

      - name: Tests
        run: pytest -q --disable-warnings --maxfail=1

      - name: Build docs (strict)
        run: mkdocs build --strict
