name: docs-build
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint mkdocs.yml loads
        run: python - << 'PY'
import sys, yaml
print("Loading mkdocs.yml …")
yaml.safe_load(open("mkdocs.yml"))
print("mkdocs.yml OK")
PY

      - name: Build docs (strict)
        run: mkdocs build --strict
